// Prisma client singleton. Prevents connection pool exhaustion from
// Next.js hot-reload creating new clients on every change.
//
// The generated client lives at ./generated/prisma (Prisma 7's new
// `prisma-client` provider emits `.ts` sources under that path). The
// file resolves to `generated/prisma/client.ts` at build time — the
// `.js` suffix is NodeNext convention and TS rewrites it to `.ts`.
//
// Before `pnpm db:generate` runs the first time, this import won't
// resolve — expected.

// @ts-expect-error — generated by `prisma generate`; see prisma/schema.prisma.
import { PrismaClient } from "./generated/prisma/client.js";

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma: PrismaClient =
  globalForPrisma.prisma ??
  new PrismaClient({
    log:
      process.env.NODE_ENV === "development"
        ? ["query", "error", "warn"]
        : ["error"],
  });

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}
